backend:
  name: github
  repo: akheeltester/overman   # change this!
  branch: main
  base_url: https://reliable-mochi-444cf1.netlify.app/    # for Netlify Identity

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "timeline"
    label: "Timeline Chapters"
    folder: "data"
    create: true
    format: "json"
    fields:
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Icon (Font Awesome class)", name: "icon", widget: "string" }
      - { label: "Image Label", name: "imageLabel", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }